print ('=' * 20)
print ('||                ||')
print ('||                ||')
print ('||      Привет    ||')
print ('||      друг!     ||')
print ('||                ||')
print ('||                ||')
print ('=' * 20)
